services: 
  bot: 
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: jukebox-bot
    env_file: 
      - .env
    restart: unless-stopped
    volumes: 
      - "./cache:/app/cache"
      - "./logs:/app/logs"
version: "2.4"