name: Push to Docker HUB

on:
  push:
    branches:
      - dev
      - stable
  release:
    types: [created]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2.3.4

      - name: Login to Docker Hub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.0.2

      - name: Extract tag name
        id: tags
        run: echo ::set-output name=name::${GITHUB_REF##*/} | sed 's/stable/latest/g'

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.1.0
        with:
          context: ./
          file: ./Dockerfile
          # platforms: linux/amd64,linux/arm64,linux/arm32 # Please see https://github.com/nodejs/docker-node/issues/1344
          platforms: linux/amd64,linux/arm64
          push: true
          tags: hazmi35/jukebox:${{ steps.tags.outputs.name }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}