name: Push to Docker HUB

on:
  push:
    branches:
      - dev
      - stable
  release:
    types: [created]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2.3.4

      - name: Login to Docker Hub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.0.2

      - name: Extract tag name
        id: tags
        run: echo ::set-output name=name::${GITHUB_REF##*/}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.1.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: hazmi35/jukebox:${{ steps.tags.outputs.name }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}